version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/iot_factory"
      FLASK_ENV: "production"
    depends_on:
      - mongodb

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://backend:5000"
    depends_on:
      - backend

  device-simulator:
    build: ./device-simulator
    environment:
      CONFIG_FILE: "/app/config.yaml"
    depends_on:
      - backend

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
