version: '3.8'

services:
  device-simulator:
    build: ./device-simulator
    depends_on:
      - backend
    environment:
      - API_ENDPOINT=http://backend:5000/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/iot_factory

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/iot_factory

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
